### ISSUE TITLE
 We can’t automatically merge this pull request.

### ISSUE THREAD

**Issue by kentyip** [githubteacher/foundations-2015-06-04#156] opened 2015-06-04 17:26 UTC
I wont let me merge my commit, this is what it says:

 We can’t automatically merge this pull request.

to resolve conflicts before continuing.

**Comment by githubstudent** [comment] 2015-06-04 17:58
@kentyip Great question, is a duplicate of #147 (which we'll answer aloud).

**Closed as completed by githubstudent** 2015-06-04 17:58 UTC
Labels: duplicate, question
